In [1]:
# Introduction to Numpy
# Numpy is an open source library of python which is used for handle scintific-calculations.

In [8]:
!pip install numpy

In [9]:
import numpy as np

In [14]:
# why numpy is better then list?
# (1). Numpy is homogenous data type and list is hetrogenous data type.
# (2). Numpy takes less memory while list take more memory.
# (3). Numpy takes less execution time while list take more time of execution.
# (4). Numpy has more functionality as compare to list.

In [15]:
a=[1,2,3,4]
type(a)

list

In [16]:
b=np.array(a)
b

array([1, 2, 3, 4])

In [17]:
type(b)

numpy.ndarray

In [18]:
a=[[1,2,3],[4,5,6],[7,8,9]]
b=np.array(a)
b

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [19]:
print("Total Rows and Columns: ",b.shape)  ## shape=n(rows),n(columns)
print("Total Elements: ",b.size)           ## size=n(rows)*n(columns)
print("Total Dimensions: ",b.ndim)         ## ndim stands for n_dimensions here 2=(x,y)

Total Rows and Columns:  (3, 3)
Total Elements:  9
Total Dimensions:  2


# User-defined Array

In [21]:
a=[]
size=int(input("Enter size:"))
for i in range(size):
  val=int(input("Enter the size:"))
  a.append(val)
# a
b=np.array(a)
b

Enter size:3
Enter the size:11
Enter the size:22
Enter the size:33


array([11, 22, 33])

# Functions in Numpy

In [22]:
# (1). Zeros()-------> It will careate an array in which all the values will be 0 in either one-dimension or multi-dimension

In [24]:
a=np.zeros(3)
a

array([0., 0., 0.])

In [27]:
a=np.zeros((3,4))
a

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [28]:
# (2).  Ones() ---------> It will create an array in which all the values will be 1 in either one dimensional and multi dimensioanl

In [31]:
a=np.ones((3,4))
a

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [32]:
# (3). eye()---------> It will create an array in which digonal positioanl elements will be 1 and rest all are 0.

In [33]:
a=np.eye(3,4)
a

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.]])

In [34]:
# (4). diag()-----> We can see custom values an digoanl position.

In [35]:
a=np.array([12,34,67,90])
a

array([12, 34, 67, 90])

In [36]:
b=np.diag(a)
b

array([[12,  0,  0,  0],
       [ 0, 34,  0,  0],
       [ 0,  0, 67,  0],
       [ 0,  0,  0, 90]])

In [39]:
# (5). Random module------1,10,3-->
# (a). Randint()---------> It will generate random numbers in a given range
a=np.random.randint(1,10,3)
a

array([1, 8, 4])

In [40]:
# (b). Rand()-------> It will generate random numbers in range 0-1
a=np.random.rand(4)
a

array([0.23107285, 0.63003951, 0.61167757, 0.84662966])

In [43]:
# (c). Seed()---> It will fix our random generated data.
np.random.seed(55)
a=np.random.randint(1,10,3)
a

array([8, 9, 6])

# Reshaping the array
n(rows)*n(columns)=n(total_elements)

In [44]:
a=np.random.randint(1,50,12)
a

array([38, 28, 34, 49, 36, 47, 31, 14, 31, 13, 25, 48])

In [46]:
a.size

12

In [47]:
# 12------> reshape
# 1*12      12*1
# 6*2,     2*6
# 4*3   3*4



In [48]:
a.reshape(2,6)


array([[38, 28, 34, 49, 36, 47],
       [31, 14, 31, 13, 25, 48]])

In [49]:
a.reshape(3,4)

array([[38, 28, 34, 49],
       [36, 47, 31, 14],
       [31, 13, 25, 48]])

In [51]:
a.reshape(4,3)

array([[38, 28, 34],
       [49, 36, 47],
       [31, 14, 31],
       [13, 25, 48]])

In [52]:
a.reshape(2,5)

ValueError: cannot reshape array of size 12 into shape (2,5)

# Operations on Array

In [53]:
a=np.arange(1,16)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [54]:
a>10

array([False, False, False, False, False, False, False, False, False,
       False,  True,  True,  True,  True,  True])

In [55]:
b=a>10
a[b]

array([11, 12, 13, 14, 15])

In [56]:
a[a%2==0]


array([ 2,  4,  6,  8, 10, 12, 14])

In [57]:
a=a.reshape(5,3)
a

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12],
       [13, 14, 15]])

In [58]:
np.sum(a)    ## total sum

np.int64(120)

In [59]:
np.sum(a,axis=0)  ## column wise sum

array([35, 40, 45])

In [61]:
np.sum(a,axis=1)  ## row wise sum

array([ 6, 15, 24, 33, 42])

In [63]:
a=np.arange(1,5).reshape(2,2)
a

array([[1, 2],
       [3, 4]])

In [65]:
b=np.arange(5,9).reshape(2,2)
b

array([[5, 6],
       [7, 8]])

In [66]:
a+b

array([[ 6,  8],
       [10, 12]])

In [67]:
a-b

array([[-4, -4],
       [-4, -4]])

In [68]:
a*b

array([[ 5, 12],
       [21, 32]])

In [70]:
a.dot(b)       ## We can multiply of matrix

array([[19, 22],
       [43, 50]])

In [71]:
a=np.array([1,2,3,4])
a**2

array([ 1,  4,  9, 16])

In [72]:
a**3

array([ 1,  8, 27, 64])

In [73]:
np.sin(a)

array([ 0.84147098,  0.90929743,  0.14112001, -0.7568025 ])

In [74]:
np.sqrt(a)

array([1.        , 1.41421356, 1.73205081, 2.        ])