In [21]:
import numpy as np

### Random Module

In [39]:
# (1).  Randint()   ---------->(It generates random numbers between conditions)
a=np.random.randint(1,120,1)
a

array([90])

In [43]:
# (2). Rand()-------------> (It gives the randeom number between 0 to 1)
a=np.random.rand(10)
a

array([0.90082072, 0.49243514, 0.66802368, 0.52198848, 0.98814101,
       0.16227348, 0.39397176, 0.48882199, 0.85224863, 0.04007312])

In [70]:
#  (3). Seed()------------> (It generates the number and fix them it means ek baar jo number create ho gye vo ab change nhi honge)
np.random.seed(1)
a=np.random.randint(1,10,3)
a

array([6, 9, 6])

# Reshaping the array

#### n(rows)*n(columns)=n(total_elements)

In [100]:
a=np.random.randint(1,50,12)
a

array([31, 33, 23, 14, 42, 10,  8, 23,  2,  1, 18,  9])

In [102]:
a.reshape(2,6)
a

array([31, 33, 23, 14, 42, 10,  8, 23,  2,  1, 18,  9])

In [104]:
a.reshape(6,2)

array([[31, 33],
       [23, 14],
       [42, 10],
       [ 8, 23],
       [ 2,  1],
       [18,  9]])

In [105]:
a.reshape(3,4)

array([[31, 33, 23, 14],
       [42, 10,  8, 23],
       [ 2,  1, 18,  9]])

In [106]:
a.reshape(4,3)

array([[31, 33, 23],
       [14, 42, 10],
       [ 8, 23,  2],
       [ 1, 18,  9]])

In [107]:
# Unique()------->
# (1). It means ek aisa array create krna jisme duplicate entries allows nhi ho.
# (2). ek ek random number ki indexing vha dekhne ko milegi of unique number.
# (3). ek original value kitne itme replicate hui h.

# arr------> unique elements of array.
# return_index=true------> Return undexing of unique elements.
# return_counts=true------->Return frequency of unique elements.


In [118]:
a=np.array([1,1,2,3,3,4,4,5,6,7,8])
a

array([1, 1, 2, 3, 3, 4, 4, 5, 6, 7, 8])

In [126]:
np.unique(a,return_index=True,return_counts=True)

(array([1, 2, 3, 4, 5, 6, 7, 8]),
 array([ 0,  2,  3,  5,  7,  8,  9, 10], dtype=int64),
 array([2, 1, 2, 2, 1, 1, 1, 1], dtype=int64))

In [130]:
# Linspace()--------------> (ek array banana jisme min value and max value k beech m same gap ki values ho)
# It will create a array in which gap of values will be equal.
# syntax:-  np.linespace(min,max,total_numbers)

In [136]:
a=np.linspace(1,2,7)
a

array([1.        , 1.16666667, 1.33333333, 1.5       , 1.66666667,
       1.83333333, 2.        ])

In [151]:
# Hstack and Vstack

# Hstack:- It will combined all the arrays in horizontally.
# Vstack:- It will combined all the arrays in vertically.

In [153]:
a=np.array([1,2,3,4,5])
b=np.array([6,7,8,9,10])
c=np.array([11,12,13,14,15])

In [157]:
np.hstack([a,b,c])

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [161]:
np.vstack([a,b,c])

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

# pandas------> It is an open source library of python which is used to handle data manupulation.

In [168]:
# !pip install pd

In [171]:
import pandas as pd

In [173]:
# Data structure of pandas
# (1). Series-------> It is one dimensional and it shows only values.
# (2). DataFrame----->It is multi-dimensoanl array and it containes value with column name.

# (a) Series

In [184]:
a=pd.Series([1,45,97,18])
a

0     1
1    45
2    97
3    18
dtype: int64

In [180]:
type(a)

pandas.core.series.Series

# (b) DataFrame

In [188]:
a={
    "Emp_id":[1,2,3,4,5],
    "Emp_Name":['Sam','Raj','Bham','Neetu','Manan'],
    "Emp_Department":['It','Hr','Finance','Jr. Dev.','Sen. Dev.'],
    "Emp_Salary":[20000,30000,40000,50000,60000]
}
a

{'Emp_id': [1, 2, 3, 4, 5],
 'Emp_Name': ['Sam', 'Raj', 'Bham', 'Neetu', 'Manan'],
 'Emp_Department': ['It', 'Hr', 'Finance', 'Jr. Dev.', 'Sen. Dev.'],
 'Emp_Salary': [20000, 30000, 40000, 50000, 60000]}

In [190]:
df=pd.DataFrame(a)
df

Emp_id Emp_Name Emp_Department  Emp_Salary
0       1      Sam             It       20000
1       2      Raj             Hr       30000
2       3     Bham        Finance       40000
3       4    Neetu       Jr. Dev.       50000
4       5    Manan      Sen. Dev.       60000

In [194]:
df.to_csv("C:\\Users\\deves\\Desktop\\New folder\\emp_info.csv",index=False)